image: node:18

definitions:
  caches:
    npm: ~/.npm
    maven: ~/.m2

pipelines:
  branches:
    master:
      - step:
          name: Build and Package App for Linux
          caches:
            - npm
            - maven
          script:
            - apt-get update && apt-get install -y maven
            - cd backend
            - mvn test
            - mvn clean package -DskipTests
            - cd ../frontend
            - npm ci
            - mkdir -p jars
            - cp ../backend/target/*.jar jars/
            - npm run build
            - npm run package-linux-arm64
            - apt-get install -y fakeroot
            - umask 0022
            - npm run debian-installer-arm64
            - cd release-builds/linux-deb

            - pipe: atlassian/bitbucket-upload-file:0.7.4
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: 'eba-uim_1.3.0_arm64.deb'

          artifacts:
            - frontend/release-builds/**