image: node:18

pipelines:
  branches:
    ebam-gerdo:
      - step:
          name: Build and Package App
          script:
            # Build backend with Maven
            - apt-get update && apt-get install -y maven
            - cd backend
            - mvn test
            - mvn clean package
            - cd ../frontend

            # Install frontend dependencies
            - npm install

            # Create jars directory and copy backend JAR
            - mkdir -p jars
            - cp ../backend/target/*.jar jars/

            # Build the Angular app
            - npm run build

            # Package for All
            - npm run package-linux-debian-x64
            - apt-get install -y fakeroot
            - npm run debian-installer-x64
            - cd release-builds/linux-deb

            # Use Bitbucket's API to upload the zip files
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: 'eba-uim_1.3.0_x64.deb'

          artifacts:
            - frontend/release-builds/**