image: node:18

definitions:
  caches:
    npm: ~/.npm
    maven: ~/.m2
    node-modules: node_modules

pipelines:
  branches:
    master:
      - step:
          name: Build and Package App
          script:
            # Build backend with Maven
            - apt-get update && apt-get install -y maven
            - cd backend
            - mvn test
            - mvn clean package
          artifacts:
            - frontend/release-builds/**
    